Samarth's NixOS and nix-darwin (outdated) setup. Heavily inspired by [[https://github.com/lccambiaghi/nixpkgs/blob/main/readme.org][lccambiaghi's setup]].

* Installation
1. Install the ~nix~ daemon if not on NixOS
2. Install ~nix-darwin~ (if on macOS)
3. Clone this repo into the =$HOME/.config= directory

* Laptop (NixOS)

This configuration is specific to my Framework 13 laptop. Change the =laptop/nixos/hardware-configuration.nix= file if on a different machine.

Rebuild the NixOS configuration with

#+BEGIN_SRC sh
NIX_PATH=${NIX_PATH}:nixos-config=${HOME}/.config/nixpkgs/laptop/nixos/configuration.nix sudo nixos-rebuild switch -I nixos-config=${HOME}/.config/nixpkgs/laptop/nixos/configuration.nix
#+END_SRC

This is aliased to =make laptop=.

* nix-darwin (outdated)
Documentation: https://daiderd.com/nix-darwin/manual/index.html#sec-options

If you modify any of the Darwin settings, run the following command to reload the configuration.

#+BEGIN_SRC sh
darwin-rebuild switch -I darwin-config=$HOME/.config/nixpkgs/darwin/configuration.nix
#+END_SRC

This is aliased to =make darwin=.

Sometimes you'll have to run the script =nix-symlink-apps-macos= if you change any Mac app settings and want the app launcher to point to the correct executable (like Emacs).

* Set up email

Generate a GPG key

#+begin_src sh
gpg --gen-key
#+end_src

Initialize the password store

#+begin_src sh
pass init samarthkishor1@gmail.com
#+end_src

Add password for gmail

#+begin_src sh
pass insert mbsync-gmail
#+end_src

Add password for UVA email

#+begin_src sh
pass insert mbsync-uva
#+end_src

Make the Maildir directories

#+begin_src sh
mkdir ~/Maildir
mkdir -p ~/Maildir/gmail
mkdir -p ~/Maildir/uva
#+end_src

Fetch the email

#+begin_src sh
cd ~/Maildir && mbsync -a
#+end_src

* What is included?
- git
- shell (zsh)
- email (mbsync)
- cli programs with ~home.packages~
- some dotfiles

* TODOs
- This setup is not fully reproducible, I can either:
  - Pin versions of package repositories via =niv=
  - Switch to using flakes once I figure it out or once it becomes stable (preferred)
- Better documentation and directory structure
