Samarth's Nix, nix-darwin, and home-manager setup. Heavily inspired by [[https://github.com/lccambiaghi/nixpkgs/blob/main/readme.org][lccambiaghi's setup]].

* Installation
1. Install ~nix~ daemon
2. Install ~nix-darwin~ (if on macOS)
3. Remove the default ~~/.config/nixpkgs~ and ~git clone https://github.com/samarthkishor/nixpkgs~
4. Run =make darwin= if on macOS, otherwise run =make switch=

* Usage

If you modify any of the Darwin settings, run =make darwin= to reload the configuration.
Sometimes you'll have to run the script =nix-symlink-apps-macos= if you change any Mac app settings and want the app launcher to point to the correct executable (like Emacs).

If you modify any of the other Nix settings, run =make switch= to reload the configuration.

* nix-darwin
Documentation: https://daiderd.com/nix-darwin/manual/index.html#sec-options
** Rebuild switch

#+BEGIN_SRC sh
darwin-rebuild switch -I darwin-config=$HOME/.config/nixpkgs/darwin/configuration.nix
#+END_SRC

This is aliased to =make darwin=

* What is included?
- emacs
- git
- shell (zsh)
- terminal (kitty)
- cli programs with ~home.packages~
- some dotfiles
* TODOs
- This setup is not fully reproducible, I can either:
  - Pin versions of package repositories via =niv=
  - Switch to using flakes once I figure it out or once it becomes stable (preferred)
- Better documentation and directory structure
